"""
Output: autogenerated name, email, and profile details.

Written in Python 3
"""

from faker import Faker

fake = Faker()
print(fake.name())
print(fake.email())
print(fake.country())

print(fake.profile())
